repos:
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.12.0
  hooks:
    - id: check-github-actions
    - id: check-github-workflows
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.10
  hooks:
    - id: cmake-format
    - id: cmake-lint
# - repo: https://github.com/pocc/pre-commit-hooks
#   rev: v1.3.5
#   hooks:
#     - id: clang-format
#     - id: clang-tidy