env:
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  no-unused-vars: 1
  no-prototype-builtins : 1
